### ISSUE TITLE
Medium for Rag

### ISSUE THREAD

**Issue by isayahc** [Josephrp/adapt-a-rag#16]
what will the RAG stack consist of?

## Roadmap

- [x] Method of loading data
    - [x] loading websites
    - [x] loading documents
- [x] Methods of chunking data
- [x] Storing chunks into vector store.
- [x] #18
- [ ] Collected the needed metadata
- [x] #19

## Additional Information

I know from prior discussions we plan to use Chroma db. Via Chroma's Client object we can interface with Langchain. Any information i am forgetting please ping.

**Comment by Josephrp** [comment]
> I know from prior discussions we plan to use Chroma db. Via Chroma's Client object we can interface with Langchain.

i therefore suggest we stick with chroma all the way from loading to chunking

**Comment by Josephrp** [comment]
solved with this : https://github.com/Josephrp/adapt-a-rag/commit/d3dedff34fd8bb110531365e28cd19258bb38230
