### ISSUE TITLE
Using vector store as a retriever for a chain or agent

### ISSUE THREAD

**Issue by Josephrp** [Josephrp/adapt-a-rag#18]
### Issue

```python
class BasicMH(dspy.Module):
...
            search_results = self.claude_model.search(question, context=context, k=self.passages_per_hop)

```

doesnt exist

### Task

Complete application logic with the retrieval agent.
- [ ] add the default model for embeddings and retrieval from DSPy/Chroma
- [ ] a retrieval agent with optimized claude prompts
- [ ] a retrieval agent with chat memory
- [ ] interface logic (only show retrieval after it's available)
