### ISSUE TITLE
Interface : create simple interface 

### ISSUE THREAD

**Issue by Josephrp** [Josephrp/adapt-a-rag#8]
### Issue 

the use needs a simple interface. 

### Tasks

- [x] decide on an interface system , for example streamlit, chainlit , something like that. 
- [x] the interface should have text input for keys
- [ ] the interface should have text input for user query
- [ ]  the interface should have a full chat bot 
- [ ] the interface might have text input / document input for synthetic data generation
- [ ] the interface might have file upload for RAG retrieval
- [ ] the interface might have separate screens for the repository loaders , the webpage search 

- **examples:**  [chatinterface](https://huggingface.co/spaces/deepseek-ai/DeepSeek-VL-7B/blob/main/app.py)

**Comment by Ariankhalfani** [comment]
our interface are using gradio lib. we need to finished the backend code first to see how the design worked
